apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  settings.js: |-
    /**
     * This is the default settings file provided by wordpress.

     **/
  
    