{{- if .Values.wordpress.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ (split "/" $.Template.Name)._2 }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  {{- with .Values.wordpress.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.wordpress.ingress.className }}
  {{- if .Values.wordpress.ingress.tls }}
  tls:
    {{- range .Values.wordpress.ingress.tls }}
    - hosts:
        {{- if $.Values.wordpress.ingress.domain }}
        - {{ $.Values.wordpress.ingress.domain | quote }}
        {{- if $.Values.wordpress.ingress.enableWWWHost }}
        - {{ printf "www.%s" $.Values.wordpress.ingress.domain | quote }}
        {{- end }}
        {{- else }}
        - {{ $.Release.Name | replace "-" "." | quote }}
        {{- if $.Values.wordpress.ingress.enableWWWHost }}
        - {{ printf "www.%s" $.Release.Name | replace "-" "." | quote }}
        {{- end }}        
        {{- end }}
      {{- if $.Values.wordpress.ingress.domain }}
      secretName: {{ $.Values.wordpress.ingress.domain }}-tls
      {{- else }}
      secretName: {{ $.Release.Name | replace "-" "." }}-tls
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.wordpress.ingress.hosts }}
    {{- if $.Values.wordpress.ingress.domain }}
    - host: {{ $.Values.wordpress.ingress.domain | quote }}
    {{- else }}
    - host: {{ $.Release.Name | replace "-" "." | quote }}
    {{- end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: wordpress
                port:
                  number: 80
          {{- end }}
    {{- end }}
    {{- if $.Values.wordpress.ingress.enableWWWHost }}
    {{- if .Values.wordpress.ingress.domain }}
    - host: {{ printf "www.%s" $.Values.wordpress.ingress.domain | quote }}
    {{- else }}
    - host: {{ printf "www.%s" $.Release.Name | replace "-" "." | quote }}
    {{- end }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: wordpress
                port:
                  number: 80
    {{- end }}