apiVersion: v1
kind: Service
metadata:
  name: {{ (split "/" $.Template.Name)._2 }}
spec:
  type: {{ .Values.wordpress.service.type }}
  selector:
    app: {{ (split "/" $.Template.Name)._2 }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.wordpress.service.port }}
      targetPort: {{ .Values.wordpress.service.port }}
