global:
    
mariadb:
  replicaCount: 1

  image:
    repository: mariadb
    tag: 10.11.6
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3306

  persistence:
    enabled: true
    size: 8Gi
  
  auth:
    mysql_root_password: wordresss
    mysql_database: mariadb
    mysql_user: wordpress
    mysql_password: wordpress

phpmyadmin:
  replicaCount: 1

  image:
    repository: phpmyadmin
    tag: 5.2.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  persistence:
    enabled: true
    size: 1Gi

  pma_host: mariadb

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: 7.2.3
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379

  persistence:
    enabled: true
    size: 1Gi

wordpress:
  replicaCount: 1

  image:
    repository: dbrosy/wordpress
    tag: cli_2.9.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  persistence:
    enabled: true
    size: 20Gi

  ingress:
    enabled: true
    enableWWWHost: false
    domain: ""
    className: ""
    annotations:
      # kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific      
    tls:
      - secretName: chart-example-tls
        hosts:
          - chart-example.local

