apiVersion: v1
kind: Secret
metadata:
  name: {{ (split "/" $.Template.Name)._2 }}-auth
type: "Opaque"
data:
  mysql_root_password: {{ .Values.mariadb.auth.mysql_root_password | b64enc }}
  mysql_database: {{ .Values.mariadb.auth.mysql_database | b64enc }}
  mysql_user: {{ .Values.mariadb.auth.mysql_user | b64enc }}
  mysql_password: {{ .Values.mariadb.auth.mysql_password | b64enc }}
