apiVersion: v1
kind: Service
metadata:
  name: {{ (split "/" $.Template.Name)._2 }}-loadbalancer
spec:
  selector:
    app: {{ (split "/" $.Template.Name)._2 }}
  ports:
    - name: webui
      protocol: TCP
      port: {{ .Values.unifi.service.webui.port }}
      targetPort: {{ .Values.unifi.service.webui.port }}
    - name: devicecomms
      protocol: TCP
      port: {{ .Values.unifi.service.devicecomms.port }}
      targetPort: {{ .Values.unifi.service.devicecomms.port }}
    - name: stun
      protocol: UDP
      port: {{ .Values.unifi.service.stun.port }}
      targetPort: {{ .Values.unifi.service.stun.port }}
  type: {{ .Values.unifi.service.type }}

